resources:
  - namespaces/shop-platform.yaml
  - auth-config.yaml
  - secrets.yaml
  - auth-mongo.yaml
  - product-mongo.yaml
  - cart-redis.yaml
  - order-mongo.yaml
  - auth-service.yaml
  - product-service.yaml
  - cart-service.yaml
  - order-service.yaml
  - frontend.yaml
  - ingress.yaml